name: Api SonarCloud CI

on:
    workflow_run:
      workflows: ['Test API, Generate Coverage, and Validate Responses']
      types: [completed]
permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
    SonarCloudAnalysis-API:
        name: SonarCloud Analysis API
        # Note: No need for 'needs: test_api' since it's in another workflow now
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
            with:
              fetch-depth: 0 # Important to fetch all history for accurate blame information
              
          - name: Download lcov artifact from Untrusted workflow
            uses: actions/download-artifact@v3
            with:
              name: coverage-report
              
          - name: Move lcov.info to api/source
            run: mv lcov.info ./api/source/
            
          - name: Analyze API with SonarCloud
            uses: SonarSource/sonarcloud-github-action@v2.0.2
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information
              SONAR_TOKEN: ${{ secrets.API_SONAR_TOKEN }} # Needed to push to SonarCloud
            with:
              # Additional arguments for the sonarcloud scanner
              projectBaseDir: ./api/source
              args: -Dsonar.projectKey=nuwcdivnpt_stig-manager-api
                -Dsonar.projectName=nuwcdivnpt_stig-manager-api
                -Dsonar.organization=nuwcdivnpt
                -Dsonar.inclusions=**/*.js
                -Dsonar.exclusions=**/node_modules/**,**/coverage-report/**
                -Dsonar.javascript.lcov.reportPaths=./lcov.info